Fix bug4821 - Some tests request an incorrectly large segment size
In FAST/LARGE segment modes, always validate the segment size
request we're about to pass into gex_Segment_Attach or gasnet_attach
fits within gasnet_getMaxLocalSegmentSize, otherwise issue a
user-friendly error message.

Example testvis output (from a docker container with default shm):
```
ERROR: node 1/4 Test requested a GASNet segment of size=16777216, but this exceeds the currently available gasnet_getMaxLocalSegmentSize()=10477568.
You may need to adjust the memory resource limits of this system/shell, otherwise adjust test parameters to reduce segment utilization requirements. (at [redacted]/gasnet/tests/test.h:1023)
```