tests: correct 0-length Attach call in testnbr
This commit follows up on the decision to prohibit zero-sized calls
to gex_Segment_Attach() by eliminating one such call in testnbr.

Without this change, `testnbh -h` was crashing on some conduits:
```
{phargrov@pcp-d-6 ibv-conduit}$ ./contrib/gasnetrun_ibv -n1 ./testnbr -h
ERROR: node 0/1 gex_Segment_QueryBound(tm, i, &_addr, NULL, &_size): Operation not permitted(1) (at /home/pcp1/phargrov/UPC/upc-runtime/gasnet/tests/test.h:1041)
*** Caught a fatal signal: SIGABRT(6) on node 0/1
NOTICE: Before reporting bugs, run with GASNET_BACKTRACE=1 in the environment to generate a backtrace.
```

This commit resolves Bug 3571 (Regression: issues with 0-length segments) as
INVALID.