ibv: improved error message for BLCR+PSHM
This commit provides better reporting of the unsupported BLCR+PSHM
configuration of ibv-conduit.  This is motivated by an end-user who
didn't know (or care) that they had BLCR installed on their cluster.
They error messages they saw made no reference to BLCR.

Before:
[...]/ibv-conduit/gasnet_core.c:2346:2: error: #error Not YET supporting PSHM
[...]/ibv-conduit/gasnet_core.c:2373:6: error: #error NOT implemented
[...]/ibv-conduit/gasnet_core.c:2386:2: error: #error Not YET supporting PSHM (and thus XRC)
[...]/ibv-conduit/gasnet_core.c: In function 'gasnetc_post_checkpoint':
[...]/ibv-conduit/gasnet_core.c:2389: error: 'shared_mem' undeclared (first use in this function)
[...]/ibv-conduit/gasnet_core.c:2389: error: (Each undeclared identifier is reported only once
[...]/ibv-conduit/gasnet_core.c:2389: error: for each function it appears in.)

After:
[...]/ibv-conduit/gasnet_core.c:2300:2: error: BLCR integration does not YET support PSHM - configure with --disable-blcr or --disable-pshm

NOTE: Ideally this configuration could be rejected at configure time.
(cherry picked from commit f3d31286024b0e8bf46289c7b5b8b1cc421f066f)