gasneti_fatalerror: add node id to boilerplate
Example:

*** FATAL ERROR (node 7): Synthetic fatal error

(cherry picked from commit a2ceea42033025ddfbfaf3d0f56d1f0f1f88f1e8)